/** MCP server.instructions — built-in hints for IDE agents. */
export const MCP_SERVER_INSTRUCTIONS = [
  'VisualQ Quality MCP — create FRT scenarios in VisualQ, run VRT/FRT, rolling page health, multi-pillar audits.',
  '',
  '>>> CREATE FRT SCENARIO <<<',
  'When the user asks for a functional test / scénario FRT / user-journey test (with MCP or in VisualQ):',
  '1. frt_find_scenarios(query=<goal>) — reuse existing featureId when matchScore >= 0.85',
  '2. create_frt_scenario(goal=<actions only>, confirm=true) — only if no strong match or forceCreate:true',
  'Optional: startPath (e.g. "/"), name. User goal may be French; Gherkin steps are always English.',
  'Do NOT put tracking payload verification in goal — use tracking_get_plan + run_tracking after the click scenario.',
  'Do NOT write Gherkin in chat. Do NOT tell the user how to import — create_frt_scenario persists the feature in VisualQ.',
  '',
  '>>> JIRA TRACKING PROOF <<<',
  'When the user asks to prove/verify a JIRA tracking ticket (preuve, payload, comment with proof):',
  '1. Read the ticket via JIRA MCP (summary + description).',
  '2. tracking_prove_jira_ticket(ticketId, reproGoal from ticket, confirm: true) — ONE call.',
  '3. Paste data.jiraMarkdown into the JIRA comment.',
  'Do NOT manually chain frt_find_scenarios, run_frt_feature, run_full_audit, or read app source code.',
  'The tool resolves intent semantically — exact rail/book names in the ticket are repro examples, not match keys.',
  '',
  'Always pass "project" (slug) on every tool unless VISUALQ_DEFAULT_PROJECT is set on the org agent key.',
  'Mutating tools require confirm: true (create_frt_scenario, create_project, run_vrt, approve_vrt_results, etc.).',
  'After run_vrt/run_baseline/run_full_audit, call wait_for_run. After async tools (crawl_site), poll get_job_status.',
  'For pillar audits (a11y, perf, seo, security, tracking, functional): run_full_audit with pillars[] — no separate run_a11y/run_tracking tools.',
  'Use get_site_health / gate_pr_quality for project KPIs — never treat a single latest run as the site score.',
  'Follow nextActions in tool responses when present.',
  'FRT: fix failures at source (prompts, binding, step catalog) — no silent selector swaps on system.* steps.',
  'Org agent keys (vq_org_live_) use MCP tools only. Project CI keys (vq_live_) are for GitHub Actions /api/ci/*.',
].join('\n')
