/** MCP server.instructions — built-in hints for IDE agents. */
export const MCP_SERVER_INSTRUCTIONS = [
  'VisualQ Quality MCP — create FRT scenarios in VisualQ, run VRT/FRT, rolling page health, multi-pillar audits.',
  '',
  '>>> CREATE FRT SCENARIO <<<',
  'When the user asks for a functional test / scénario FRT / user-journey test (with MCP or in VisualQ):',
  '1. frt_find_scenarios(query=<goal>) — reuse existing featureId when matchScore >= 0.85',
  '2. create_frt_scenario(goal=<actions only>, confirm=true) — only if no strong match or forceCreate:true',
  'Optional: startPath (e.g. "/"), name. User goal may be French; Gherkin steps are always English.',
  'Do NOT put tracking payload verification in goal — use tracking_prove_jira_ticket for JIRA proof.',
  'Do NOT write Gherkin in chat. Do NOT tell the user how to import — create_frt_scenario persists the feature in VisualQ.',
  '',
  '>>> JIRA TRACKING PROOF <<<',
  'When the user asks to prove/verify a JIRA tracking ticket (preuve, payload, comment with proof):',
  '1. Read the ticket via JIRA MCP (summary + description).',
  '2. tracking_prove_jira_ticket(ticketId, reproGoal from ticket, confirm: true) — ONE call (async).',
  '3. Poll get_job_status until status completed; read proofVerdict, proofContract, investigationLadder.',
  '4. If proofVerdict is proven AND proofContract.mayClaimTicketFixed: paste result.jiraMarkdown verbatim into JIRA.',
  '5. If NOT proven: say NON (quote proofOutcome.headline). Follow investigationLadder:',
  '   - Step 1: identify scenario (data.scenario or frt_find_scenarios read-only)',
  '   - Step 2: frt_get_feature(featureId, ticketId) — read Gherkin + scenarioCoverageAnalysis',
  '   - Step 3: propose manual recette on site (human_handoff) — do NOT run run_full_audit',
  'FORBIDDEN after failed prove: run_full_audit, tracking_get_audit_report for JIRA conclusion, gate_pr_quality, get_site_health as ticket proof, reading app source.',
  'FORBIDDEN chain for initial proof: frt_find → create → run_frt → run_full_audit (use tracking_prove_jira_ticket first).',
  'Global scores (757/757) are SITE-WIDE — never prove a specific JIRA ticket.',
  '',
  'Always pass "project" (slug) on every tool unless VISUALQ_DEFAULT_PROJECT is set on the org agent key.',
  'Mutating tools require confirm: true (create_frt_scenario, create_project, run_vrt, approve_vrt_results, etc.).',
  'After run_vrt/run_baseline, call wait_for_run. After async tools (crawl_site, tracking_prove_jira_ticket), poll get_job_status.',
  'For site-wide pillar audits (not JIRA ticket proof): run_full_audit with pillars[].',
  'Use get_site_health / gate_pr_quality for project KPIs only — never as JIRA ticket proof.',
  'Follow nextActions in tool responses when present.',
  'FRT: fix failures at source (prompts, binding, step catalog) — no silent selector swaps on system.* steps.',
  'Org agent keys (vq_org_live_) use MCP tools only. Project CI keys (vq_live_) are for GitHub Actions /api/ci/*.',
].join('\n')
